//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kidsvt1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Input_values {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input_values() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kidsvt1.Input values", typeof(Input_values).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-0,2-0,8-1; 1-1,2-x,8-0; 1-x,2-1,8-0.
        /// </summary>
        internal static string Element1 {
            get {
                return ResourceManager.GetString("Element1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-1,9-0; 3-0,9-1.
        /// </summary>
        internal static string Element2 {
            get {
                return ResourceManager.GetString("Element2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-1,6-1,10-0; 5-0,6-x,10-1; 5-x,6-0,10-1.
        /// </summary>
        internal static string Element3 {
            get {
                return ResourceManager.GetString("Element3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-0,7-x,10-x,11-0; 4-x,7-0,10-x,11-0; 4-x,7-x,10-0,11-0; 4-1,7-1,10-1,11-1.
        /// </summary>
        internal static string Element4 {
            get {
                return ResourceManager.GetString("Element4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9-x,11-1,12-1; 9-1,11-x,12-1; 9-0,11-0,12-0.
        /// </summary>
        internal static string Element5 {
            get {
                return ResourceManager.GetString("Element5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-0,12-x,13-0; 8-x,12-0,13-0; 8-1,12-1,13-1.
        /// </summary>
        internal static string Element6 {
            get {
                return ResourceManager.GetString("Element6", resourceCulture);
            }
        }
    }
}
